# Generated by Django 5.0.4 on 2024-06-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
        ('pastures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='pasture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pastures.pasture'),
        ),
    ]
