# Generated by Django 5.0.4 on 2024-07-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_lot_pasture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='cow_count',
        ),
    ]
