path: C:\Users\Manuel\Desktop\Dataset conteo\
train: frames_cow_id
val: frames_cow_id
nc: 16

# Clases
names:
  0: dog
  1: person
  2: cat
  3: tv
  4: car
  5: meatballs
  6: marinara sauce
  7: tomato soup
  8: chicken noodle soup
  9: french onion soup
  10: chicken breast
  11: ribs
  12: pulled pork
  13: hamburger
  14: cavity
  15: cow
