# Generated by Django 5.0.4 on 2024-06-29 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranch', to='ranch.ranch')),
            ],
        ),
    ]
