# Generated by Django 5.0.4 on 2024-07-07 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0002_lot_pasture'),
        ('pastures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('video', 'Video')], default='manual', max_length=10)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_history', to='lots.lot')),
                ('pasture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pastures.pasture')),
            ],
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('processed', models.BooleanField(default=False)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_uploads', to='lots.lot')),
            ],
        ),
    ]
