# Generated by Django 5.0.4 on 2024-07-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_countings', '0001_initial'),
        ('pastures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counthistory',
            name='method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='counthistory',
            name='pasture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pastures.pasture'),
            preserve_default=False,
        ),
    ]
