# Generated by Django 5.0.4 on 2024-07-14 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_countings', '0002_alter_counthistory_method_alter_counthistory_pasture'),
        ('lots', '0003_remove_lot_cow_count'),
        ('pastures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='lot',
        ),
        migrations.CreateModel(
            name='CowCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_count', models.IntegerField()),
                ('method', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=250)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_history', to='lots.lot')),
                ('pasture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastures.pasture')),
            ],
        ),
        migrations.DeleteModel(
            name='CountHistory',
        ),
        migrations.DeleteModel(
            name='VideoUpload',
        ),
    ]
