# Generated by Django 5.0.4 on 2024-07-14 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_countings', '0003_remove_videoupload_lot_cowcount_delete_counthistory_and_more'),
        ('pastures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowcount',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cowcount',
            name='pasture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pastures.pasture'),
        ),
    ]
