# Generated by Django 5.0.4 on 2024-07-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_countings', '0004_alter_cowcount_date_alter_cowcount_pasture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowcount',
            name='comment',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cowcount',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('video', 'Video')], default='manual', max_length=10),
        ),
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_video', models.FileField(upload_to='uploaded_videos/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('cow_count', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='cattle_countings.cowcount')),
            ],
        ),
    ]
