# Generated by Django 5.0.4 on 2024-07-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_countings', '0005_alter_cowcount_comment_alter_cowcount_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
