# Generated by Django 5.0.4 on 2024-07-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_countings', '0006_uploadedvideo_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedvideo',
            name='processed',
        ),
    ]
