# Generated by Django 5.0.4 on 2024-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_countings', '0007_remove_uploadedvideo_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
